import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const termina = localFont({
  src: [
    {
      path: "../public/fonts/termina/TerminaTest-Regular.otf",
     style : "normal" ,
    },
  ],
  variable: "--font-termina",
});

const ivy = localFont({
  src: [
    {
      path: "../public/fonts/ivy/ivy-presto-display.otf",
      style: "normal",
    },
  ],
  variable: "--font-ivy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${termina.variable} ${ivy.variable}`}>
      <body>{children}</body>
    </html>
  );
}
